# RAG系统配置文件
base_dir: ./

model_config:
  # 嵌入模型配置
  embedding_model:
    name: openai/clip-vit-base-patch32
    provider: huggingface_transformers
    device: auto  # auto, cuda, cpu
    
text_processing_config:
  # 文本分块配置
  chunk_size: 1000
  chunk_overlap: 200
  
  # PDF处理配置
  pdf_page_chunk: true
  max_pdf_pages: 50
  
  # CSV处理配置
  csv_row_chunk: true
  csv_encoding: utf-8

vector_store_config:
  # 数据库配置
  database_type: "dual"  # dual: PDF和CSV分别存储
  
  # PDF数据库配置
  pdf_database:
    persist_directory: ./chroma_db/pdf_db
    collection_name: pdf_documents
    search_kwargs:
      k: 5
  
  # CSV数据库配置
  csv_database:
    persist_directory: ./chroma_db/csv_db
    collection_name: csv_documents
    search_kwargs:
      k: 5
